In [9]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

第一章 tensor张量
===============
  + 标量（Scalar）是只有大小，没有方向的量，如1，2，3等
  + 向量（Vector）是有大小和方向的量，其实就是一串数字，如(1,2)
  + 矩阵（Matrix）是好几个向量拍成一排合并而成的一堆数字，如[1,2;3,4]
  <img src="https://upload-images.jianshu.io/upload_images/68960-86fe03c0bd55821f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/327/format/webp">如图，我们可以看出，矩阵是二维的，向量是一维的，标量是零维的。<br>
  <span style="font-size:18px;font-weight:bold;">其实标量，向量，矩阵它们三个也是张量，标量是零维的张量，向量是一维的张量，矩阵是二维的张量。</span>
  <img src="https://upload-images.jianshu.io/upload_images/68960-84adb05ed57ff266.png?imageMogr2/auto-orient/">张量就是按照任意维排列的一堆数字的推广。如图所示，矩阵不过是三维张量下的一个二维切面。要找到三维张量下的一个标量，需要三个维度的坐标来定位。<br>
  <a href="https://www.jianshu.com/p/5ae644748f21/">参考链接献上</a>

In [4]:
#打印torch版本
print(torch.__version__)

0.4.1


判断是否可以使用GPU，返回True代表可以

In [6]:
print(torch.cuda.is_available())

True


#### **torch.tensor**是一个包含多个同类数据类型数据的多维矩阵，默认是torch.FloatTensor。
- **device:**这个参数表示了tensor将会在哪个设备上分配内存。它包含了设备的类型（cpu、cuda）和可选设备序号。如果这个值是缺省的，那么默认为当前的活动设备类型。
- **require_grad:**这个标志表明这个tensor的操作是否会被pytorch的自动微分系统（Autograd）记录其操作过程，以便后续自动求导。
- **layout：**表示了tensor的内存分布方式。目前，pytorch支持torch.strided方式以及实验性质地支持torch.sparse_coo。前者是目前普遍的使用方式。每一个strided tensor都关联一个torch.storage以保存其数据。

In [25]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

In [26]:
x.dtype

torch.float32

In [27]:
torch.is_tensor(x)

True

Tensor跟tensor的区别是：Tensor定义后已经初始化了，而tensor则没有初始化

In [28]:
a1 = torch.Tensor(2,2)

In [29]:
a2 = torch.Tensor(4,2,3)

In [30]:
y = w * x + b

In [31]:
y.backward()

In [32]:
x.grad

tensor(2.)

In [34]:
h = torch.Tensor(5, 3)  # 构造一个未初始化的5*3的矩阵
h = torch.rand(5, 3)  # 构造一个随机初始化的矩阵
h # 此处在notebook中输出x的值来查看具体的x内容
h.size()

torch.Size([5, 3])

In [35]:
h

tensor([[0.4382, 0.9775, 0.4099],
        [0.1197, 0.5300, 0.1714],
        [0.7189, 0.2981, 0.9877],
        [0.3738, 0.2048, 0.3262],
        [0.4958, 0.6278, 0.5569]])

In [36]:
k = torch.rand(5,3)

In [39]:
k

tensor([[0.4115, 0.6888, 0.6987],
        [0.3963, 0.5501, 0.4177],
        [0.3099, 0.8434, 0.1130],
        [0.0279, 0.9514, 0.2996],
        [0.9395, 0.4572, 0.2034]])

In [38]:
h + k

tensor([[0.8497, 1.6664, 1.1086],
        [0.5161, 1.0801, 0.5892],
        [1.0288, 1.1416, 1.1007],
        [0.4017, 1.1562, 0.6258],
        [1.4353, 1.0850, 0.7603]])

In [40]:
torch.add(h,k)

tensor([[0.8497, 1.6664, 1.1086],
        [0.5161, 1.0801, 0.5892],
        [1.0288, 1.1416, 1.1007],
        [0.4017, 1.1562, 0.6258],
        [1.4353, 1.0850, 0.7603]])

In [41]:
# 另外输出tensor也有两种写法
result = torch.Tensor(5, 3) # 语法一
torch.add(h, k, out=result) # 语法二
# y.add_(x) # 将y与x相加

tensor([[0.8497, 1.6664, 1.1086],
        [0.5161, 1.0801, 0.5892],
        [1.0288, 1.1416, 1.1007],
        [0.4017, 1.1562, 0.6258],
        [1.4353, 1.0850, 0.7603]])

 **特别注明：**任何可以改变tensor内容的操作都会在方法名后加一个下划线'_'<br>
 例如：x.copy_(y), x.t_(), 这俩都会改变x的值。

In [42]:
h.add_(k)

tensor([[0.8497, 1.6664, 1.1086],
        [0.5161, 1.0801, 0.5892],
        [1.0288, 1.1416, 1.1007],
        [0.4017, 1.1562, 0.6258],
        [1.4353, 1.0850, 0.7603]])

Torch的Tensor和numpy的array可以相互转换。注意Torch的Tensor和numpy的array会共享他们的存储空间，修改一个会导致另外的一个也被修改。

In [62]:
#展示他们之间的相互转化
t1 = torch.ones(10)
t2 = t1.numpy()

In [63]:
t1

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
t2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [65]:
#更改一个后，另一个也随之更改
t1.add_(1)

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [66]:
t2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32)

In [61]:
#将numpy数组转化为tensor
a = np.ones(10)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


In [59]:
# 另外除了CharTensor之外，所有的tensor都可以在CPU运算和GPU预算之间相互转换
# 使用CUDA函数来将Tensor移动到GPU上
# 当CUDA可用时会进行GPU的运算
if torch.cuda.is_available():
    h = h.cuda()
    k = k.cuda()
    print(h + k)

tensor([[1.2612, 2.3552, 1.8072],
        [0.9124, 1.6301, 1.0069],
        [1.3387, 1.9850, 1.2137],
        [0.4296, 2.1076, 0.9254],
        [2.3748, 1.5421, 0.9638]], device='cuda:0')
