In [2]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
from torch.autograd import Variable
import torchvision.transforms as transforms

第二章 autograd 及Variable
======================
- **Autograd: 自动微分**<br>
　　autograd包是PyTorch中神经网络的核心, 它可以为基于tensor的的所有操作提供自动微分的功能, 这是一个逐个运行的框架, 意味着反向传播是根据你的代码来运行的, 并且每一次的迭代运行都可能不同.
- **Variable**<br>
   tensor是硬币的话，那Variable就是钱包，它记录着里面的钱的多少，和钱的流向.
   <img src="https://pic4.zhimg.com/80/v2-ab0e724afb75f6ba74ebb99f27e3a2b7_hd.jpg">   　　　　　　　　variable是tensor的外包装，data属性存储着tensor数据，grad属性存储关于该变量的导数，creator是代表该变量的创造者.<br>
   　　autograd.Variable 是包的中央类, 它包裹着Tensor, 支持几乎所有Tensor的操作,并附加额外的属性, 在进行操作以后, 通过调用.backward()来计算梯度, 通过.data来访问原始raw data (tensor), 并将变量梯度累加到.grad。<br>
   　　Variable 与 Function互连并建立一个非循环图，编码完整的计算历史。 每个变量都有一个 .grad_fn 属性，它引用了一个已经创建了 Variable 的 操作,如加减乘除等（除了用户创建的变量代替creator is None 即第一个运算节点, .grad_fn为空)
     <img src="https://pic2.zhimg.com/80/v2-0a938a33a77b14171cb17f2bbafc0ba1_hd.jpg">
   <a href="https://zhuanlan.zhihu.com/p/34298983">==》参加链接</a>

In [3]:
#Tensor是存在Variable中的.data里的，而cpu和gpu的数据是通过 .cpu()和.cuda()来转换的
a=Variable(torch.Tensor([1]),requires_grad=True).cuda()

In [4]:
a

tensor([1.], device='cuda:0', grad_fn=<CopyBackwards>)

In [5]:
a.data

tensor([1.], device='cuda:0')

In [6]:
a.cpu()

tensor([1.], grad_fn=<CopyBackwards>)

In [7]:
a.cpu().data

tensor([1.])

In [8]:
a.grad

## 自动求导：
对于中间变量，一旦它们完成了自身反传的使命，grad就会被释放掉。另外启始节点的grad_fn为空
<img src="https://pic2.zhimg.com/80/v2-d6b51005dd1593a0541e3ca16e805809_hd.jpg">

In [11]:
a=Variable(torch.Tensor([1]),requires_grad=True) 
b=Variable(torch.Tensor([2]),requires_grad=True)
c=Variable(torch.Tensor([3]),requires_grad=True)

In [12]:
d=a+b
e=d+c
e.backward()
print(a.grad,b.grad,c.grad)

tensor([1.]) tensor([1.]) tensor([1.])


In [13]:
d.grad #中间梯度值不保存，为空

In [14]:
a.grad_fn ##第一个节点的.grad_fn为空

In [15]:
e.grad_fn